name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        env:
          TF_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}  # Use the token from GitHub Secrets
        run: terraform init

      - name: Terraform Apply
        env:
          GITHUB_TOKEN: ${{ secrets.TF_INIT_TOKEN }}
          TF_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}  # Use the token from GitHub Secrets
        run: |
          terraform workspace select github-management || terraform workspace new github-management
          terraform apply -auto-approve 

